import { z } from 'zod'

export const projectSchema = z.object({
  title: z.string().min(3, 'Título requerido'),
  description: z.string().min(10, 'Descripción mínima de 10 caracteres'),
  teacher: z.string().min(3, 'Docente requerido'),
  course: z.string().min(2, 'Curso requerido'),
  area: z.string().min(2, 'Área requerida'),
  experienceType: z.string().min(3, 'Tipo de experiencia requerido'),
  link: z.string().url('Link inválido').optional().nullable().or(z.literal('')),
  isReusable: z.boolean().optional(),
  status: z.enum(['Cargado', 'Borrador generado', 'En revisión', 'Publicado', 'Archivado']).optional(),
  improvedTitle: z.string().optional().nullable(),
  generatedSummary: z.string().optional().nullable(),
  objectives: z.string().optional().nullable(),
  mainActivities: z.string().optional().nullable(),
  resourcesUsed: z.string().optional().nullable(),
  finalProducts: z.string().optional().nullable(),
  evidenceDescription: z.string().optional().nullable(),
  reuseSuggestions: z.string().optional().nullable(),
  improvementSuggestions: z.string().optional().nullable(),
  suggestedTags: z.string().optional().nullable(),
  introActivities: z.string().optional().nullable(),
  developmentActivities: z.string().optional().nullable(),
  closingActivities: z.string().optional().nullable(),
  assessmentCriteria: z.string().optional().nullable(),
  rubric: z.string().optional().nullable(),
  interdisciplinarySuggestions: z.string().optional().nullable(),
  adaptations: z.string().optional().nullable(),
  requiredResources: z.string().optional().nullable(),
  estimatedTimeline: z.string().optional().nullable(),
  studentReflectionQuestions: z.string().optional().nullable(),
  quizQuestions: z.string().optional().nullable(),
  trueFalse: z.string().optional().nullable(),
  multipleChoice: z.string().optional().nullable(),
  wordSearch: z.string().optional().nullable(),
  crossword: z.string().optional().nullable(),
  memoryGame: z.string().optional().nullable(),
  bingoConcepts: z.string().optional().nullable(),
  challengeCards: z.string().optional().nullable(),
  rolePlayingGame: z.string().optional().nullable(),
  reflectionGame: z.string().optional().nullable(),
  presentationTitle: z.string().optional().nullable(),
  presentationSubtitle: z.string().optional().nullable(),
  slides: z.string().optional().nullable(),
  oralScript: z.string().optional().nullable(),
  visualSuggestions: z.string().optional().nullable(),
  closingMessage: z.string().optional().nullable()
})
